k3s_version: "v1.29.0+k3s1"
domain_base: "34.159.144.113.nip.io"
flux_github_owner: "ondrejnr"
flux_github_repo: "mon"
flux_github_token: "{{ vault_github_token }}"
docker_hub_user: "ondrejnr1"
postgres_password: "{{ vault_postgres_password }}"
postgresql_version: "15"
vault_grafana_admin_password: "{{ vault_grafana_admin_password }}"
