$ANSIBLE_VAULT;1.1;AES256
35656533643733306661623135623634373531623366393166326663383834616134646165643133
6338313636623561343466623563333038636563393939390a353537316231313335643536656437
38336333353864383835366562666533373232663365396433313062383666663762323461616564
3633376465333934350a306632633238643939346663666334656139323863646235343433326261
34663662613261303537336434643234366261313264623135313264393136656532306630393162
64366236616466313632613165616134346366303261623366333862396639633635653933346633
66363531653534383436333335363635626333306666623836616338366131316263343761616437
35633931626635633735333363343264646466653838623966356366303335633533306565393837
63643232393061356538353036643231396664336663326431653630613061666436633534653438
6530663663643066393863623030383539626431643735353464
