apiVersion: v1
items:
- apiVersion: networking.k8s.io/v1
  kind: Ingress
  metadata:
    annotations:
      argocd.argoproj.io/tracking-id: nginx-stack:networking.k8s.io/Ingress:web-stack/nginx-ingress
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"networking.k8s.io/v1","kind":"Ingress","metadata":{"annotations":{"argocd.argoproj.io/tracking-id":"nginx-stack:networking.k8s.io/Ingress:web-stack/nginx-ingress"},"name":"nginx-ingress","namespace":"web-stack"},"spec":{"ingressClassName":"nginx","rules":[{"host":"nginx.34.89.208.249.nip.io","http":{"paths":[{"backend":{"service":{"name":"nginx-balancer","port":{"number":80}}},"path":"/","pathType":"Prefix"}]}}]}}
    name: nginx-ingress
    namespace: web-stack
  spec:
    ingressClassName: nginx
    rules:
    - host: nginx.34.89.208.249.nip.io
      http:
        paths:
        - backend:
            service:
              name: nginx-balancer
              port:
                number: 80
          path: /
          pathType: Prefix
      ingress:
      - ip: 10.156.15.202
kind: List
metadata:
