---
- name: Create Apache Ingress
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: networking.k8s.io/v1
      kind: Ingress
      metadata:
        name: apache-ingress
        namespace: lamp
        annotations:
          kubernetes.io/ingress.class: traefik
      spec:
        rules:
          - host: "apache.{{ domain_base }}"
            http:
              paths:
                - path: /
                  pathType: Prefix
                  backend:
                    service:
                      name: apache-php
                      port:
                        number: 80
