apiVersion: v1
items:
- apiVersion: networking.k8s.io/v1
  kind: Ingress
  metadata:
    annotations:
      argocd.argoproj.io/tracking-id: lamp-stack:networking.k8s.io/Ingress:lamp/bank-final
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"networking.k8s.io/v1","kind":"Ingress","metadata":{"annotations":{"argocd.argoproj.io/tracking-id":"lamp-stack:networking.k8s.io/Ingress:lamp/bank-final","nginx.ingress.kubernetes.io/backend-protocol":"HTTP","nginx.ingress.kubernetes.io/ssl-redirect":"false"},"generation":1,"name":"bank-final","namespace":"lamp"},"spec":{"ingressClassName":"nginx","loadBalancer":{"ingress":[{"ip":"10.156.15.202"}]},"rules":[{"host":"bank.34.89.208.249.nip.io","http":{"paths":[{"backend":{"service":{"name":"apache-php","port":{"number":80}}},"path":"/","pathType":"Prefix"}]}}],"tls":[{"hosts":["bank.34.89.208.249.nip.io"],"secretName":"bank-tls-secret"}]}}
      nginx.ingress.kubernetes.io/backend-protocol: HTTP
      nginx.ingress.kubernetes.io/ssl-redirect: "false"
    name: bank-final
    namespace: lamp
  spec:
    ingressClassName: nginx
    rules:
    - host: bank.34.89.208.249.nip.io
      http:
        paths:
        - backend:
            service:
              name: apache-php
              port:
                number: 80
          path: /
          pathType: Prefix
    tls:
    - hosts:
      - bank.34.89.208.249.nip.io
      secretName: bank-tls-secret
      ingress:
      - ip: 10.156.15.202
kind: List
metadata:
