apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      argocd.argoproj.io/tracking-id: lamp-stack:/Service:lamp/apache-php
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{"argocd.argoproj.io/tracking-id":"lamp-stack:/Service:lamp/apache-php"},"name":"apache-php","namespace":"lamp"},"spec":{"clusterIP":"10.43.44.28","clusterIPs":["10.43.44.28"],"internalTrafficPolicy":"Cluster","ipFamilies":["IPv4"],"ipFamilyPolicy":"SingleStack","loadBalancer":{},"ports":[{"name":"http","port":80,"protocol":"TCP","targetPort":80},{"name":"apache-metrics","port":9117,"protocol":"TCP","targetPort":9117},{"name":"php-metrics","port":9253,"protocol":"TCP","targetPort":9253}],"selector":{"app":"apache-php"},"sessionAffinity":"None","type":"ClusterIP"}}
    name: apache-php
    namespace: lamp
  spec:
    clusterIP: 10.43.44.28
    clusterIPs:
    - 10.43.44.28
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
    - name: apache-metrics
      port: 9117
      protocol: TCP
      targetPort: 9117
    - name: php-metrics
      port: 9253
      protocol: TCP
      targetPort: 9253
    selector:
      app: apache-php
    sessionAffinity: None
    type: ClusterIP
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"postgresql","namespace":"lamp"},"spec":{"ports":[{"port":5432,"targetPort":5432}],"selector":{"app":"postgresql"}}}
    name: postgresql
    namespace: lamp
  spec:
    clusterIP: 10.43.255.50
    clusterIPs:
    - 10.43.255.50
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - port: 5432
      protocol: TCP
      targetPort: 5432
    selector:
      app: postgresql
    sessionAffinity: None
    type: ClusterIP
kind: List
metadata:
