apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      argocd.argoproj.io/tracking-id: web-stack:/Service:web/nginx-service
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{"argocd.argoproj.io/tracking-id":"web-stack:/Service:web/nginx-service"},"name":"nginx-service","namespace":"web"},"spec":{"ports":[{"port":80,"targetPort":80}],"selector":{"app":"nginx-web"}}}
    name: nginx-service
    namespace: web
  spec:
    clusterIP: 10.43.39.155
    clusterIPs:
    - 10.43.39.155
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - port: 80
      protocol: TCP
      targetPort: 80
    selector:
      app: nginx-web
    sessionAffinity: None
    type: ClusterIP
kind: List
metadata:
