apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      argocd.argoproj.io/tracking-id: web-stack:/Service:web/nginx-service
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{"argocd.argoproj.io/tracking-id":"web-stack:/Service:web/nginx-service"},"name":"nginx-service","namespace":"web"},"spec":{"ports":[{"port":80,"targetPort":80}],"selector":{"app":"nginx-web"}}}
    creationTimestamp: "2026-02-25T17:38:59Z"
    labels:
      kustomize.toolkit.fluxcd.io/name: flux-system
      kustomize.toolkit.fluxcd.io/namespace: flux-system
    name: nginx-service
    namespace: web
    resourceVersion: "196585"
    uid: 2c3721f7-d756-489d-a882-2a0366de366c
  spec:
    clusterIP: 10.43.235.116
    clusterIPs:
    - 10.43.235.116
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - port: 80
      protocol: TCP
      targetPort: 80
    selector:
      app: nginx-web
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
kind: List
metadata:
  resourceVersion: ""
