apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      argocd.argoproj.io/tracking-id: web-stack-stack:/Service:web-stack/nginx-balancer
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{"argocd.argoproj.io/tracking-id":"web-stack-stack:/Service:web-stack/nginx-balancer"},"name":"nginx-balancer","namespace":"web-stack"},"spec":{"ports":[{"port":80,"targetPort":80}],"selector":{"app":"nginx-app"}}}
    name: nginx-balancer
    namespace: web-stack
  spec:
    clusterIP: 10.43.24.177
    clusterIPs:
    - 10.43.24.177
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - port: 80
      protocol: TCP
      targetPort: 80
    selector:
      app: nginx-app
    sessionAffinity: None
    type: ClusterIP
kind: List
metadata:
