apiVersion: v1
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      argocd.argoproj.io/tracking-id: online-retail:apps/Deployment:online-retail/cnpg-cloudnative-pg
      deployment.kubernetes.io/revision: "1"
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"argocd.argoproj.io/tracking-id":"online-retail:apps/Deployment:online-retail/cnpg-cloudnative-pg","deployment.kubernetes.io/revision":"1","meta.helm.sh/release-name":"cnpg","meta.helm.sh/release-namespace":"online-retail"},"creationTimestamp":"2026-02-26T23:15:53Z","generation":1,"labels":{"app.kubernetes.io/instance":"cnpg","app.kubernetes.io/managed-by":"Helm","app.kubernetes.io/name":"cloudnative-pg","app.kubernetes.io/version":"1.28.1","helm.sh/chart":"cloudnative-pg-0.27.1"},"name":"cnpg-cloudnative-pg","namespace":"online-retail","resourceVersion":"224959","uid":"9cf768ea-8565-4815-b1f1-5c26f7b6343d"},"spec":{"progressDeadlineSeconds":600,"replicas":1,"revisionHistoryLimit":10,"selector":{"matchLabels":{"app.kubernetes.io/instance":"cnpg","app.kubernetes.io/name":"cloudnative-pg"}},"strategy":{"rollingUpdate":{"maxSurge":"25%","maxUnavailable":"25%"},"type":"RollingUpdate"},"template":{"metadata":{"annotations":{"checksum/config":"c6d824cab2b336f792fa153c3145dcf95399b7bfc85b0ddf8f2c2f160b4cc0f8","checksum/monitoring-config":"f4b6bbd38741fa98699f27ca297970abcaadc8dc0a238d9278d583701c0f21bb","checksum/rbac":"b28aecac2ad2293e5ccda1cf1c81652abec98fd07f505df626090fc8584e7a59"},"labels":{"app.kubernetes.io/instance":"cnpg","app.kubernetes.io/name":"cloudnative-pg"}},"spec":{"containers":[{"args":["controller","--leader-elect","--max-concurrent-reconciles=10","--config-map-name=cnpg-controller-manager-config","--webhook-port=9443"],"command":["/manager"],"env":[{"name":"OPERATOR_IMAGE_NAME","value":"ghcr.io/cloudnative-pg/cloudnative-pg:1.28.1"},{"name":"OPERATOR_NAMESPACE","valueFrom":{"fieldRef":{"apiVersion":"v1","fieldPath":"metadata.namespace"}}},{"name":"MONITORING_QUERIES_CONFIGMAP","value":"cnpg-default-monitoring"}],"image":"ghcr.io/cloudnative-pg/cloudnative-pg:1.28.1","imagePullPolicy":"IfNotPresent","livenessProbe":{"failureThreshold":3,"httpGet":{"path":"/readyz","port":"webhook-server","scheme":"HTTPS"},"initialDelaySeconds":3,"periodSeconds":10,"successThreshold":1,"timeoutSeconds":1},"name":"manager","ports":[{"containerPort":8080,"name":"metrics","protocol":"TCP"},{"containerPort":9443,"name":"webhook-server","protocol":"TCP"}],"readinessProbe":{"failureThreshold":3,"httpGet":{"path":"/readyz","port":"webhook-server","scheme":"HTTPS"},"initialDelaySeconds":3,"periodSeconds":10,"successThreshold":1,"timeoutSeconds":1},"resources":{},"securityContext":{"allowPrivilegeEscalation":false,"capabilities":{"drop":["ALL"]},"readOnlyRootFilesystem":true,"runAsGroup":10001,"runAsUser":10001,"seccompProfile":{"type":"RuntimeDefault"}},"startupProbe":{"failureThreshold":6,"httpGet":{"path":"/readyz","port":"webhook-server","scheme":"HTTPS"},"periodSeconds":5,"successThreshold":1,"timeoutSeconds":1},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","volumeMounts":[{"mountPath":"/controller","name":"scratch-data"},{"mountPath":"/run/secrets/cnpg.io/webhook","name":"webhook-certificates"}]}],"dnsPolicy":"ClusterFirst","restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{"runAsNonRoot":true,"seccompProfile":{"type":"RuntimeDefault"}},"serviceAccount":"cnpg-cloudnative-pg","serviceAccountName":"cnpg-cloudnative-pg","terminationGracePeriodSeconds":10,"volumes":[{"emptyDir":{},"name":"scratch-data"},{"name":"webhook-certificates","secret":{"defaultMode":420,"optional":true,"secretName":"cnpg-webhook-cert"}}]}}},"status":{"availableReplicas":1,"conditions":[{"lastTransitionTime":"2026-02-26T23:16:00Z","lastUpdateTime":"2026-02-26T23:16:00Z","message":"Deployment has minimum availability.","reason":"MinimumReplicasAvailable","status":"True","type":"Available"},{"lastTransitionTime":"2026-02-26T23:15:53Z","lastUpdateTime":"2026-02-26T23:16:00Z","message":"ReplicaSet \"cnpg-cloudnative-pg-86d55887f8\" has successfully progressed.","reason":"NewReplicaSetAvailable","status":"True","type":"Progressing"}],"observedGeneration":1,"readyReplicas":1,"replicas":1,"updatedReplicas":1}}
      meta.helm.sh/release-name: cnpg
      meta.helm.sh/release-namespace: online-retail
    creationTimestamp: "2026-02-26T23:15:53Z"
    generation: 2
    labels:
      app.kubernetes.io/instance: cnpg
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: cloudnative-pg
      app.kubernetes.io/version: 1.28.1
      helm.sh/chart: cloudnative-pg-0.27.1
    name: cnpg-cloudnative-pg
    namespace: online-retail
    resourceVersion: "256537"
    uid: 9cf768ea-8565-4815-b1f1-5c26f7b6343d
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app.kubernetes.io/instance: cnpg
        app.kubernetes.io/name: cloudnative-pg
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        annotations:
          checksum/config: c6d824cab2b336f792fa153c3145dcf95399b7bfc85b0ddf8f2c2f160b4cc0f8
          checksum/monitoring-config: f4b6bbd38741fa98699f27ca297970abcaadc8dc0a238d9278d583701c0f21bb
          checksum/rbac: b28aecac2ad2293e5ccda1cf1c81652abec98fd07f505df626090fc8584e7a59
        labels:
          app.kubernetes.io/instance: cnpg
          app.kubernetes.io/name: cloudnative-pg
      spec:
        containers:
        - args:
          - controller
          - --leader-elect
          - --max-concurrent-reconciles=10
          - --config-map-name=cnpg-controller-manager-config
          - --webhook-port=9443
          command:
          - /manager
          env:
          - name: OPERATOR_IMAGE_NAME
            value: ghcr.io/cloudnative-pg/cloudnative-pg:1.28.1
          - name: OPERATOR_NAMESPACE
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
          - name: MONITORING_QUERIES_CONFIGMAP
            value: cnpg-default-monitoring
          image: ghcr.io/cloudnative-pg/cloudnative-pg:1.28.1
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /readyz
              port: webhook-server
              scheme: HTTPS
            initialDelaySeconds: 3
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          name: manager
          ports:
          - containerPort: 8080
            name: metrics
            protocol: TCP
          - containerPort: 9443
            name: webhook-server
            protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /readyz
              port: webhook-server
              scheme: HTTPS
            initialDelaySeconds: 3
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources: {}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            readOnlyRootFilesystem: true
            runAsGroup: 10001
            runAsUser: 10001
            seccompProfile:
              type: RuntimeDefault
          startupProbe:
            failureThreshold: 6
            httpGet:
              path: /readyz
              port: webhook-server
              scheme: HTTPS
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 1
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /controller
            name: scratch-data
          - mountPath: /run/secrets/cnpg.io/webhook
            name: webhook-certificates
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext:
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault
        serviceAccount: cnpg-cloudnative-pg
        serviceAccountName: cnpg-cloudnative-pg
        terminationGracePeriodSeconds: 10
        volumes:
        - emptyDir: {}
          name: scratch-data
        - name: webhook-certificates
          secret:
            defaultMode: 420
            optional: true
            secretName: cnpg-webhook-cert
  status:
    availableReplicas: 1
    conditions:
    - lastTransitionTime: "2026-02-26T23:16:00Z"
      lastUpdateTime: "2026-02-26T23:16:00Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    - lastTransitionTime: "2026-02-26T23:15:53Z"
      lastUpdateTime: "2026-02-26T23:16:00Z"
      message: ReplicaSet "cnpg-cloudnative-pg-86d55887f8" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    observedGeneration: 2
    readyReplicas: 1
    replicas: 1
    updatedReplicas: 1
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "7"
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"frontend","namespace":"online-retail"},"spec":{"replicas":2,"selector":{"matchLabels":{"app":"frontend"}},"template":{"metadata":{"annotations":{"prometheus.io/port":"80","prometheus.io/scrape":"true"},"labels":{"app":"frontend"}},"spec":{"containers":[{"image":"ondrejnr1/frontend:latest","name":"frontend","ports":[{"containerPort":80}]}]}}}}
    creationTimestamp: "2026-02-26T23:40:04Z"
    generation: 7
    name: frontend
    namespace: online-retail
    resourceVersion: "256482"
    uid: f51dc0dc-4f5e-4028-b150-9cac9892b498
  spec:
    progressDeadlineSeconds: 600
    replicas: 2
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: frontend
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        annotations:
          prometheus.io/path: /metrics
          prometheus.io/port: "80"
          prometheus.io/scrape: "true"
        labels:
          app: frontend
      spec:
        containers:
        - image: ondrejnr1/frontend:latest
          imagePullPolicy: Always
          name: frontend
          ports:
          - containerPort: 80
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        imagePullSecrets:
        - name: regcred
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
  status:
    availableReplicas: 2
    conditions:
    - lastTransitionTime: "2026-02-26T23:50:43Z"
      lastUpdateTime: "2026-02-26T23:50:43Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    - lastTransitionTime: "2026-02-26T23:40:04Z"
      lastUpdateTime: "2026-02-27T06:14:31Z"
      message: ReplicaSet "frontend-74dd68c6bd" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    observedGeneration: 7
    readyReplicas: 2
    replicas: 2
    updatedReplicas: 2
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "5"
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"product-service","namespace":"online-retail"},"spec":{"replicas":2,"selector":{"matchLabels":{"app":"product-service"}},"template":{"metadata":{"annotations":{"prometheus.io/port":"8080","prometheus.io/scrape":"true"},"labels":{"app":"product-service"}},"spec":{"containers":[{"env":[{"name":"DB_HOST","value":"postgres-rw"},{"name":"DB_PORT","value":"5432"},{"name":"DB_NAME","value":"products"},{"name":"DB_USER","valueFrom":{"secretKeyRef":{"key":"username","name":"postgres-secret"}}},{"name":"DB_PASSWORD","valueFrom":{"secretKeyRef":{"key":"password","name":"postgres-secret"}}}],"image":"ondrejnr1/product-service:latest","name":"product-service","ports":[{"containerPort":8080}]}],"imagePullSecrets":[{"name":"regcred"}]}}}}
    creationTimestamp: "2026-02-26T23:44:48Z"
    generation: 5
    name: product-service
    namespace: online-retail
    resourceVersion: "256479"
    uid: 4eea4b29-d9af-42d8-930e-22c07d3a74e7
  spec:
    progressDeadlineSeconds: 600
    replicas: 2
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: product-service
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        annotations:
          prometheus.io/path: /metrics
          prometheus.io/port: "8080"
          prometheus.io/scrape: "true"
        labels:
          app: product-service
      spec:
        containers:
        - env:
          - name: DB_HOST
            value: postgres-rw
          - name: DB_PORT
            value: "5432"
          - name: DB_NAME
            value: products
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                key: username
                name: postgres-secret
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                key: password
                name: postgres-secret
          image: ondrejnr1/product-service:latest
          imagePullPolicy: Always
          name: product-service
          ports:
          - containerPort: 8080
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        imagePullSecrets:
        - name: regcred
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
  status:
    availableReplicas: 2
    conditions:
    - lastTransitionTime: "2026-02-26T23:51:29Z"
      lastUpdateTime: "2026-02-26T23:51:29Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    - lastTransitionTime: "2026-02-26T23:44:48Z"
      lastUpdateTime: "2026-02-27T06:14:31Z"
      message: ReplicaSet "product-service-664998ffd8" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    observedGeneration: 5
    readyReplicas: 2
    replicas: 2
    updatedReplicas: 2
kind: List
metadata:
  resourceVersion: ""
