apiVersion: v1
items:
- apiVersion: networking.k8s.io/v1
  kind: Ingress
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"networking.k8s.io/v1","kind":"Ingress","metadata":{"annotations":{"nginx.ingress.kubernetes.io/rewrite-target":"/$1","nginx.ingress.kubernetes.io/use-regex":"true"},"name":"api-gateway","namespace":"online-retail"},"spec":{"ingressClassName":"nginx","rules":[{"host":"api.34.89.208.249.nip.io","http":{"paths":[{"backend":{"service":{"name":"product-service","port":{"number":8080}}},"path":"/(products.*)","pathType":"Prefix"},{"backend":{"service":{"name":"order-service","port":{"number":8081}}},"path":"/(orders.*)","pathType":"Prefix"},{"backend":{"service":{"name":"user-service","port":{"number":8082}}},"path":"/(users.*)","pathType":"Prefix"},{"backend":{"service":{"name":"payment-service","port":{"number":8083}}},"path":"/(payments.*)","pathType":"Prefix"}]}}]}}
      nginx.ingress.kubernetes.io/rewrite-target: /$1
      nginx.ingress.kubernetes.io/use-regex: "true"
    creationTimestamp: "2026-02-27T10:40:40Z"
    generation: 2
    name: api-gateway
    namespace: online-retail
    resourceVersion: "281135"
    uid: 6603e023-c405-4715-96c0-2ff0ddb8284d
  spec:
    ingressClassName: nginx
    rules:
    - host: api.34.89.208.249.nip.io
      http:
        paths:
        - backend:
            service:
              name: product-service
              port:
                number: 8080
          path: /(products.*)
          pathType: Prefix
        - backend:
            service:
              name: order-service
              port:
                number: 8081
          path: /(orders.*)
          pathType: Prefix
        - backend:
            service:
              name: user-service
              port:
                number: 8082
          path: /(users.*)
          pathType: Prefix
        - backend:
            service:
              name: payment-service
              port:
                number: 8083
          path: /(payments.*)
          pathType: Prefix
  status:
    loadBalancer:
      ingress:
      - ip: 10.156.15.202
- apiVersion: networking.k8s.io/v1
  kind: Ingress
  metadata:
    annotations:
      argocd.argoproj.io/tracking-id: online-retail:networking.k8s.io/Ingress:online-retail/frontend
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"networking.k8s.io/v1","kind":"Ingress","metadata":{"annotations":{"argocd.argoproj.io/tracking-id":"online-retail:networking.k8s.io/Ingress:online-retail/frontend","nginx.ingress.kubernetes.io/rewrite-target":"/"},"creationTimestamp":"2026-02-26T23:40:04Z","generation":1,"name":"frontend","namespace":"online-retail","resourceVersion":"256546","uid":"1ceadfa3-1755-4b77-bcff-ea2bf3fe69ec"},"spec":{"ingressClassName":"nginx","rules":[{"host":"shop.34.89.208.249.nip.io","http":{"paths":[{"backend":{"service":{"name":"frontend","port":{"number":80}}},"path":"/","pathType":"Prefix"}]}}]},"status":{"loadBalancer":{"ingress":[{"ip":"10.156.15.202"}]}}}
      nginx.ingress.kubernetes.io/rewrite-target: /
    creationTimestamp: "2026-02-26T23:40:04Z"
    generation: 1
    name: frontend
    namespace: online-retail
    resourceVersion: "263602"
    uid: 1ceadfa3-1755-4b77-bcff-ea2bf3fe69ec
  spec:
    ingressClassName: nginx
    rules:
    - host: shop.34.89.208.249.nip.io
      http:
        paths:
        - backend:
            service:
              name: frontend
              port:
                number: 80
          path: /
          pathType: Prefix
  status:
    loadBalancer:
      ingress:
      - ip: 10.156.15.202
kind: List
metadata:
  resourceVersion: ""
