apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      argocd.argoproj.io/tracking-id: online-retail:/Service:online-retail/cnpg-webhook-service
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{"argocd.argoproj.io/tracking-id":"online-retail:/Service:online-retail/cnpg-webhook-service","meta.helm.sh/release-name":"cnpg","meta.helm.sh/release-namespace":"online-retail"},"creationTimestamp":"2026-02-26T23:15:53Z","labels":{"app.kubernetes.io/instance":"cnpg","app.kubernetes.io/managed-by":"Helm","app.kubernetes.io/name":"cloudnative-pg","app.kubernetes.io/version":"1.28.1","helm.sh/chart":"cloudnative-pg-0.27.1"},"name":"cnpg-webhook-service","namespace":"online-retail","resourceVersion":"224913","uid":"a60fd93f-1ee1-40b0-8c1a-7020c1e6d531"},"spec":{"clusterIP":"10.43.200.190","clusterIPs":["10.43.200.190"],"internalTrafficPolicy":"Cluster","ipFamilies":["IPv4"],"ipFamilyPolicy":"SingleStack","ports":[{"name":"webhook-server","port":443,"protocol":"TCP","targetPort":"webhook-server"}],"selector":{"app.kubernetes.io/instance":"cnpg","app.kubernetes.io/name":"cloudnative-pg"},"sessionAffinity":"None","type":"ClusterIP"},"status":{"loadBalancer":{}}}
      meta.helm.sh/release-name: cnpg
      meta.helm.sh/release-namespace: online-retail
    creationTimestamp: "2026-02-26T23:15:53Z"
    labels:
      app.kubernetes.io/instance: cnpg
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: cloudnative-pg
      app.kubernetes.io/version: 1.28.1
      helm.sh/chart: cloudnative-pg-0.27.1
    name: cnpg-webhook-service
    namespace: online-retail
    resourceVersion: "256521"
    uid: a60fd93f-1ee1-40b0-8c1a-7020c1e6d531
  spec:
    clusterIP: 10.43.200.190
    clusterIPs:
    - 10.43.200.190
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: webhook-server
      port: 443
      protocol: TCP
      targetPort: webhook-server
    selector:
      app.kubernetes.io/instance: cnpg
      app.kubernetes.io/name: cloudnative-pg
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      argocd.argoproj.io/tracking-id: online-retail:/Service:online-retail/frontend
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{"argocd.argoproj.io/tracking-id":"online-retail:/Service:online-retail/frontend"},"creationTimestamp":"2026-02-26T23:40:04Z","name":"frontend","namespace":"online-retail","resourceVersion":"227660","uid":"6c1c7d37-9396-48d1-ae82-a7f9807feca8"},"spec":{"clusterIP":"10.43.120.174","clusterIPs":["10.43.120.174"],"internalTrafficPolicy":"Cluster","ipFamilies":["IPv4"],"ipFamilyPolicy":"SingleStack","ports":[{"port":80,"protocol":"TCP","targetPort":80}],"selector":{"app":"frontend"},"sessionAffinity":"None","type":"ClusterIP"},"status":{"loadBalancer":{}}}
    creationTimestamp: "2026-02-26T23:40:04Z"
    name: frontend
    namespace: online-retail
    resourceVersion: "256523"
    uid: 6c1c7d37-9396-48d1-ae82-a7f9807feca8
  spec:
    clusterIP: 10.43.120.174
    clusterIPs:
    - 10.43.120.174
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - port: 80
      protocol: TCP
      targetPort: 80
    selector:
      app: frontend
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      cnpg.io/operatorVersion: 1.28.1
    creationTimestamp: "2026-02-27T07:09:08Z"
    labels:
      app.kubernetes.io/component: database
      app.kubernetes.io/instance: postgres
      app.kubernetes.io/managed-by: cloudnative-pg
      app.kubernetes.io/name: postgresql
      app.kubernetes.io/version: "18"
      cnpg.io/cluster: postgres
    name: postgres-r
    namespace: online-retail
    ownerReferences:
    - apiVersion: postgresql.cnpg.io/v1
      controller: true
      kind: Cluster
      name: postgres
      uid: 5340d90b-08e3-4bd1-b0cd-015e7999f484
    resourceVersion: "260900"
    uid: 36f1b623-4588-4085-82d1-93b1a1587a67
  spec:
    clusterIP: 10.43.226.6
    clusterIPs:
    - 10.43.226.6
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: postgres
      port: 5432
      protocol: TCP
      targetPort: 5432
    selector:
      cnpg.io/cluster: postgres
      cnpg.io/podRole: instance
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      cnpg.io/operatorVersion: 1.28.1
    creationTimestamp: "2026-02-27T07:09:08Z"
    labels:
      app.kubernetes.io/component: database
      app.kubernetes.io/instance: postgres
      app.kubernetes.io/managed-by: cloudnative-pg
      app.kubernetes.io/name: postgresql
      app.kubernetes.io/version: "18"
      cnpg.io/cluster: postgres
    name: postgres-ro
    namespace: online-retail
    ownerReferences:
    - apiVersion: postgresql.cnpg.io/v1
      controller: true
      kind: Cluster
      name: postgres
      uid: 5340d90b-08e3-4bd1-b0cd-015e7999f484
    resourceVersion: "260904"
    uid: 08e157ba-425a-4846-a297-aa29004a7014
  spec:
    clusterIP: 10.43.130.207
    clusterIPs:
    - 10.43.130.207
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: postgres
      port: 5432
      protocol: TCP
      targetPort: 5432
    selector:
      cnpg.io/cluster: postgres
      cnpg.io/instanceRole: replica
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      cnpg.io/operatorVersion: 1.28.1
    creationTimestamp: "2026-02-27T07:09:08Z"
    labels:
      app.kubernetes.io/component: database
      app.kubernetes.io/instance: postgres
      app.kubernetes.io/managed-by: cloudnative-pg
      app.kubernetes.io/name: postgresql
      app.kubernetes.io/version: "18"
      cnpg.io/cluster: postgres
    name: postgres-rw
    namespace: online-retail
    ownerReferences:
    - apiVersion: postgresql.cnpg.io/v1
      controller: true
      kind: Cluster
      name: postgres
      uid: 5340d90b-08e3-4bd1-b0cd-015e7999f484
    resourceVersion: "260908"
    uid: 59e6c5f4-c6ca-4f73-85da-d63d11c2194c
  spec:
    clusterIP: 10.43.121.60
    clusterIPs:
    - 10.43.121.60
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: postgres
      port: 5432
      protocol: TCP
      targetPort: 5432
    selector:
      cnpg.io/cluster: postgres
      cnpg.io/instanceRole: primary
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      argocd.argoproj.io/tracking-id: online-retail:/Service:online-retail/product-service
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{"argocd.argoproj.io/tracking-id":"online-retail:/Service:online-retail/product-service"},"creationTimestamp":"2026-02-26T23:44:48Z","name":"product-service","namespace":"online-retail","resourceVersion":"228158","uid":"a16ef72c-1e5d-46f2-ab0b-2c47f687be40"},"spec":{"clusterIP":"10.43.136.85","clusterIPs":["10.43.136.85"],"internalTrafficPolicy":"Cluster","ipFamilies":["IPv4"],"ipFamilyPolicy":"SingleStack","ports":[{"port":8080,"protocol":"TCP","targetPort":8080}],"selector":{"app":"product-service"},"sessionAffinity":"None","type":"ClusterIP"},"status":{"loadBalancer":{}}}
    creationTimestamp: "2026-02-26T23:44:48Z"
    name: product-service
    namespace: online-retail
    resourceVersion: "256522"
    uid: a16ef72c-1e5d-46f2-ab0b-2c47f687be40
  spec:
    clusterIP: 10.43.136.85
    clusterIPs:
    - 10.43.136.85
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: product-service
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
kind: List
metadata:
  resourceVersion: ""
