apiVersion: v1
items:
- apiVersion: v1
  data:
    bank-status.json: "{\n  \"title\": \"Bank Infrastructure Status\",\n  \"panels\"\
      : [\n    {\n      \"title\": \"Apache Pods (Scaling)\",\n      \"type\": \"\
      stat\",\n      \"targets\": [{ \"expr\": \"kube_deployment_status_replicas{deployment='apache-php'}\"\
      \ }]\n    },\n    {\n      \"title\": \"Transaction Volume\",\n      \"type\"\
      : \"graph\",\n      \"targets\": [{ \"expr\": \"rate(node_network_receive_bytes_total[5m])\"\
      \ }]\n    }\n  ]\n}\n"
  kind: ConfigMap
  metadata:
    creationTimestamp: '2026-02-25T18:48:27Z'
    labels:
      grafana_dashboard: '1'
    name: bank-grafana-dashboard
    namespace: monitoring
    resourceVersion: '29193'
    uid: cc35afea-9c50-4c55-a444-d7758cf02e75
- apiVersion: v1
  data:
    datasources.yaml: "apiVersion: 1\ndatasources:\n- name: Prometheus\n  type: prometheus\n\
      \  url: http://prometheus.monitoring:9090\n  access: proxy\n  isDefault: true\n"
  kind: ConfigMap
  metadata:
    annotations:
      argocd.argoproj.io/tracking-id: monitoring-stack:/ConfigMap:monitoring/grafana-datasources
      kubectl.kubernetes.io/last-applied-configuration: '{"apiVersion":"v1","data":{"datasources.yaml":"apiVersion:
        1\ndatasources:\n- name: Prometheus\n  type: prometheus\n  url: http://prometheus.monitoring:9090\n  access:
        proxy\n  isDefault: true\n"},"kind":"ConfigMap","metadata":{"annotations":{"argocd.argoproj.io/tracking-id":"monitoring-stack:/ConfigMap:monitoring/grafana-datasources"},"name":"grafana-datasources","namespace":"monitoring"}}

        '
    creationTimestamp: '2026-02-25T17:38:59Z'
    labels:
      kustomize.toolkit.fluxcd.io/name: flux-system
      kustomize.toolkit.fluxcd.io/namespace: flux-system
    name: grafana-datasources
    namespace: monitoring
    resourceVersion: '169189'
    uid: b3e8364b-fa60-4472-9e54-62c9031fd6c0
- apiVersion: v1
  data:
    ca.crt: '-----BEGIN CERTIFICATE-----

      MIIBdzCCAR2gAwIBAgIBADAKBggqhkjOPQQDAjAjMSEwHwYDVQQDDBhrM3Mtc2Vy

      dmVyLWNhQDE3NzIwMjYxMDUwHhcNMjYwMjI1MTMyODI1WhcNMzYwMjIzMTMyODI1

      WjAjMSEwHwYDVQQDDBhrM3Mtc2VydmVyLWNhQDE3NzIwMjYxMDUwWTATBgcqhkjO

      PQIBBggqhkjOPQMBBwNCAAQmMwFxPzFfutsOk73AwmN9a7oWm0jyevkVBqVHQ5gV

      0e952oBQveMPbtJ82s5JB2isVYM7DRXLiHcKGLn0Vh0ao0IwQDAOBgNVHQ8BAf8E

      BAMCAqQwDwYDVR0TAQH/BAUwAwEB/zAdBgNVHQ4EFgQUG3RhGTthqrEFSGLhlb18

      ciRUIPgwCgYIKoZIzj0EAwIDSAAwRQIhAIPJHd8LCfa00hpdZVhTdu4KOT+NbjXF

      nmI0hgUSqoxAAiB1Sw5XKkkCOKOxAaqtCRVlO7jzhidAmtJkCY6auLYHVg==

      -----END CERTIFICATE-----

      '
  kind: ConfigMap
  metadata:
    annotations:
      kubernetes.io/description: Contains a CA bundle that can be used to verify the
        kube-apiserver when using internal endpoints such as the internal service
        IP or kubernetes.default.svc. No other usage is guaranteed across distributions
        of Kubernetes clusters.
    creationTimestamp: '2026-02-25T17:38:54Z'
    name: kube-root-ca.crt
    namespace: monitoring
    resourceVersion: '22885'
    uid: e9e8ff69-0bf4-4cf3-883f-49abaa767404
- apiVersion: v1
  data:
    prometheus.yml: "global:\n  scrape_interval: 15s\nscrape_configs:\n  - job_name:\
      \ 'prometheus'\n    static_configs:\n      - targets: ['localhost:9090']\n \
      \ - job_name: 'node-exporter'\n    static_configs:\n      - targets: ['node-exporter.monitoring.svc.cluster.local:9100']\n\
      \  - job_name: 'apache'\n    static_configs:\n      - targets: ['apache-php.lamp:9117']\n\
      \  - job_name: 'phpfpm'\n    static_configs:\n      - targets: ['apache-php.lamp:9253']\n\
      \  - job_name: 'postgresql'\n    static_configs:\n      - targets: ['postgresql.lamp:9187']\n\
      \  - job_name: 'grafana'\n    static_configs:\n      - targets: ['grafana.monitoring:80']\n"
  kind: ConfigMap
  metadata:
    annotations:
      argocd.argoproj.io/tracking-id: monitoring-stack:/ConfigMap:monitoring/prometheus-config
      kubectl.kubernetes.io/last-applied-configuration: '{"apiVersion":"v1","data":{"prometheus.yml":"global:\n  scrape_interval:
        15s\nscrape_configs:\n  - job_name: ''prometheus''\n    static_configs:\n      -
        targets: [''localhost:9090'']\n  - job_name: ''node-exporter''\n    static_configs:\n      -
        targets: [''node-exporter.monitoring.svc.cluster.local:9100'']\n  - job_name:
        ''apache''\n    static_configs:\n      - targets: [''apache-php.lamp:9117'']\n  -
        job_name: ''phpfpm''\n    static_configs:\n      - targets: [''apache-php.lamp:9253'']\n  -
        job_name: ''postgresql''\n    static_configs:\n      - targets: [''postgresql.lamp:9187'']\n  -
        job_name: ''grafana''\n    static_configs:\n      - targets: [''grafana.monitoring:80'']\n"},"kind":"ConfigMap","metadata":{"annotations":{"argocd.argoproj.io/tracking-id":"monitoring-stack:/ConfigMap:monitoring/prometheus-config"},"name":"prometheus-config","namespace":"monitoring"}}

        '
    creationTimestamp: '2026-02-25T17:38:59Z'
    labels:
      kustomize.toolkit.fluxcd.io/name: flux-system
      kustomize.toolkit.fluxcd.io/namespace: flux-system
    name: prometheus-config
    namespace: monitoring
    resourceVersion: '169188'
    uid: b8e1536c-5525-42c8-95d3-74c5367919a5
kind: List
metadata: {}
