apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      argocd.argoproj.io/tracking-id: monitoring-stack:/Service:monitoring/alertmanager
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{"argocd.argoproj.io/tracking-id":"monitoring-stack:/Service:monitoring/alertmanager"},"name":"alertmanager","namespace":"monitoring"},"spec":{"ports":[{"port":9093,"targetPort":9093}],"selector":{"app":"alertmanager"}}}
    name: alertmanager
    namespace: monitoring
  spec:
    clusterIP: 10.43.28.29
    clusterIPs:
    - 10.43.28.29
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - port: 9093
      protocol: TCP
      targetPort: 9093
    selector:
      app: alertmanager
    sessionAffinity: None
    type: ClusterIP
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      argocd.argoproj.io/tracking-id: monitoring-stack:/Service:monitoring/grafana
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{"argocd.argoproj.io/tracking-id":"monitoring-stack:/Service:monitoring/grafana"},"name":"grafana","namespace":"monitoring"},"spec":{"ports":[{"port":80,"targetPort":3000}],"selector":{"app":"grafana"}}}
    name: grafana
    namespace: monitoring
  spec:
    clusterIP: 10.43.28.169
    clusterIPs:
    - 10.43.28.169
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - port: 80
      protocol: TCP
      targetPort: 3000
    selector:
      app: grafana
    sessionAffinity: None
    type: ClusterIP
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      argocd.argoproj.io/tracking-id: monitoring-stack:/Service:monitoring/node-exporter
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{"argocd.argoproj.io/tracking-id":"monitoring-stack:/Service:monitoring/node-exporter"},"name":"node-exporter","namespace":"monitoring"},"spec":{"ports":[{"port":9100,"targetPort":9100}],"selector":{"app":"node-exporter"}}}
    name: node-exporter
    namespace: monitoring
  spec:
    clusterIP: 10.43.59.30
    clusterIPs:
    - 10.43.59.30
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - port: 9100
      protocol: TCP
      targetPort: 9100
    selector:
      app: node-exporter
    sessionAffinity: None
    type: ClusterIP
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      argocd.argoproj.io/tracking-id: monitoring-stack:/Service:monitoring/prometheus
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{"argocd.argoproj.io/tracking-id":"monitoring-stack:/Service:monitoring/prometheus"},"name":"prometheus","namespace":"monitoring"},"spec":{"ports":[{"port":9090,"targetPort":9090}],"selector":{"app":"prometheus"}}}
    name: prometheus
    namespace: monitoring
  spec:
    clusterIP: 10.43.173.216
    clusterIPs:
    - 10.43.173.216
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - port: 9090
      protocol: TCP
      targetPort: 9090
    selector:
      app: prometheus
    sessionAffinity: None
    type: ClusterIP
kind: List
metadata:
