apiVersion: v1
items:
- apiVersion: v1
  data:
    password: UHdtY3JhWE1zWDBvZFhNWQ==
  kind: Secret
  metadata:
    name: argocd-initial-admin-secret
    namespace: argocd
  type: Opaque
- apiVersion: v1
  kind: Secret
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Secret","metadata":{"annotations":{},"labels":{"app.kubernetes.io/component":"notifications-controller","app.kubernetes.io/name":"argocd-notifications-controller","app.kubernetes.io/part-of":"argocd"},"name":"argocd-notifications-secret","namespace":"argocd"},"type":"Opaque"}
    labels:
      app.kubernetes.io/component: notifications-controller
      app.kubernetes.io/name: argocd-notifications-controller
      app.kubernetes.io/part-of: argocd
    name: argocd-notifications-secret
    namespace: argocd
  type: Opaque
- apiVersion: v1
  data:
    auth: aUdQNEZvWVk3dGt6WDN0cA==
  kind: Secret
  metadata:
    name: argocd-redis
    namespace: argocd
  type: Opaque
- apiVersion: v1
  data:
    admin.password: JDJhJDEwJFczWFY3Wm9zWU1aOHZvNzZUaUo1dGUwZ0s3TGZmMFV3MDExT1lvSWNEejdBU0VRYWxuRXky
    admin.passwordMtime: MjAyNi0wMi0yNlQxODoyODoyOVo=
    server.secretkey: ejUrU3l3WFNiQldMa2ZtRG1YOVFyRG80OUxJMGhMTHlQKzIwMlVxRUo5WT0=
    tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURZekNDQWt1Z0F3SUJBZ0lSQUtoYVIyVHBjTlBkRGhUWk9KTG9NSFF3RFFZSktvWklodmNOQVFFTEJRQXcKRWpFUU1BNEdBMVVFQ2hNSFFYSm5ieUJEUkRBZUZ3MHlOakF5TWpZeE9ESTRNekJhRncweU56QXlNall4T0RJNApNekJhTUJJeEVEQU9CZ05WQkFvVEIwRnlaMjhnUTBRd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUJEd0F3CmdnRUtBb0lCQVFDY2JpQlFQYU8vVzc5MEMvcU5lRDNSYUhUamNQTndsb1lKUkpvYWJYb0xXbFBkMWlrQnlaamIKSXVsbmF1ODlQaEd2NC80V2JLUkFxcGljc1VVcUxNeDJOa25kZFpmZjFMa1l1Zmx3enRnWXRieTlueC9jVHZjdgpwaVdGN0gxZnNmMTlCdFpNbk5Vbi9md2VBTDdBOFRiZGh4ZkYxeDVYMVB3ZElmNDBvcm8zNnZ5cWd6VDBBWXg4CnBhL0pZZEtTMDFKbWVvSE9CVGd6QzZ2S0dVaWxWK1ZaREQ1SkdjazlqcVA0NXhBN2czdi9CZEtSbDlsVWZtNG8KN2VNUVR6ZXVhNzZCZ0lna2oxZDRhVjJLdDI5NUYrQXVtNXl1VHFWeVdBNW5tRFQ1QTRuK1VkNWVuajV5ajliRwpnQjB0OFNCbFUzV3FFUnlubG5QdjdGSk9CT01WWEZqMUFnTUJBQUdqZ2JNd2diQXdEZ1lEVlIwUEFRSC9CQVFECkFnV2dNQk1HQTFVZEpRUU1NQW9HQ0NzR0FRVUZCd01CTUF3R0ExVWRFd0VCL3dRQ01BQXdld1lEVlIwUkJIUXcKY29JSmJHOWpZV3hvYjNOMGdnMWhjbWR2WTJRdGMyVnlkbVZ5Z2hSaGNtZHZZMlF0YzJWeWRtVnlMbUZ5WjI5agpaSUlZWVhKbmIyTmtMWE5sY25abGNpNWhjbWR2WTJRdWMzWmpnaVpoY21kdlkyUXRjMlZ5ZG1WeUxtRnlaMjlqClpDNXpkbU11WTJ4MWMzUmxjaTVzYjJOaGJEQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFQQ3ZSUUp2WG9oRGQKM0FYSDdObzhKRlYyOUplRTRaejNtQ3llUVM1NFBZQUF0OTJTQWRDMG05dGFVelhYemJqWDRlTUtkTTRNMGtmbwpYZ1Z6U0p0aERISTZjQ1E0OTVlcUs2a3FLTTZ3R0R6NTBneU0vYVlzS1JQWVh1TUs3Kzg2bGVOR0dBdjJGYk0zCm81bEZhZGUxdi9TUFBFaFUyaXBNUWJvRGFFNGxTN2l0NkNuSHBJZnVNcktsak5NZkg1ME56NUJCRWRlcnBlaXMKc3pNZ1FhVFdOOVpWalI5UTBHRVBkbDJ0a25kb1h4dGJKazFCUmRKNzQrSmZhT3Z2dHVFWHcrV2Q1L0pESlZ6UQoxUDAzN1VKQTNycTJJcDkySUU2UHVYUCs3Z1p4NnBBWXZjRHJVVnZMaGV2SDFVQWRJVUxncnJnZUZjLzJ3bU85CnQzYzNITTVHQlE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    tls.key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb3dJQkFBS0NBUUVBbkc0Z1VEMmp2MXUvZEF2NmpYZzkwV2gwNDNEemNKYUdDVVNhR20xNkMxcFQzZFlwCkFjbVkyeUxwWjJydlBUNFJyK1ArRm15a1FLcVluTEZGS2l6TWRqWkozWFdYMzlTNUdMbjVjTTdZR0xXOHZaOGYKM0U3M0w2WWxoZXg5WDdIOWZRYldUSnpWSi8zOEhnQyt3UEUyM1ljWHhkY2VWOVQ4SFNIK05LSzZOK3I4cW9NMAo5QUdNZktXdnlXSFNrdE5TWm5xQnpnVTRNd3VyeWhsSXBWZmxXUXcrU1JuSlBZNmorT2NRTzRONy93WFNrWmZaClZINXVLTzNqRUU4M3JtdStnWUNJSkk5WGVHbGRpcmR2ZVJmZ0xwdWNyazZsY2xnT1o1ZzArUU9KL2xIZVhwNCsKY28vV3hvQWRMZkVnWlZOMXFoRWNwNVp6Nyt4U1RnVGpGVnhZOVFJREFRQUJBb0lCQUFtOUVXWHRjSFJKVWZIMwpqUEdodXJkK3VVZ3ZqL2hDWnJYTS80c0ZwY052TENselc3b3d3c05odVFZbk1oMnQ3NHZ6dGEzUHRhb1E5TTlNCmVmSFdPQ1JqM05WY3JNZlNobk56b0lQVlhMNnRFY0w4VlE5eUd4RnNWb212MzE1RnhuSXlLc1U2UGtydkZQTUoKT05icUxYQTlLTTI0UnJ0UkZ5RDVMTW82RnozRDJtZmFOREd3NUlmZk9rSFpLaFlKelhCTlU0b0NydWVIT05NVQp6R3hYVzd5TXRsYU50VEVEWmcxN1dHc1J3N1RoODl1Nnh3Wk1GT3ZCc0xHM21BNFlxc0pyUG1jdVpFRlNDM2kxCkxGWC84M1RrZU1hV1MxYVkyMGIrUnZ6dHVZa256UjdQTnNSbXRuQlhhVG5vdnNyMmMwWWI2TkY0NlNFeUU1WjUKY0F1ZnZBRUNnWUVBd01BSWp0YWpuaUUwTTdOSnNCTE42aVJJMForTzJvR2dwc0J4Qm5Za0JETUpKeHlrWVpPZAp1WWlaam5HWVlObzRWNHQvU25NdXVvMGUyUTJ3bGpLMXRJaTA1N1FkeExJaExML1g2YTdsNWV1d2FVVDhuTU1kCktLaXQxSWdXMTltMzBnNktHTFVxRy9KRDNUWEhIUEZjTnprVmxucEx6WDIxUlBVQStLVXNHSkVDZ1lFQXo4TUoKZEMwY1NTb0Q3SFZBaS9ZOWFLRGtKUzRTYXh0ekIyY3J6YWh3bktMNDNyL0gvbFVTbXhMWnI1RVBVdkpBWWhJNgpoTVlDc3gzbld4MDBteHBKRDB5L2h6Qmt6d2NrUUM0NGpoL0M4KzhZaGdzQ21uSzdTQ08yVEtuYU9EeWNxb1NECk81bHFFYnBFcjFKa3N1Z1hldVI4RitqcW5NYllZaVQvZmJKMkRDVUNnWUJXa1dqR2prdnA1MHZFdEk4eHp5QkEKT28raDVpR0lyWk56a1JheUtqayswWlVZeGRwbUlLQkVCYi9Cbys4bUFKd3haV3VFQ250QU9jVlRBcnorbUVQWAprMVo4Z2Y2a3FzUVBqeEh2MkNkVXZpZjYvNHJjOVJ5UmVFQ3FKWHpzOE5HSVBCTjF5VmZpT1VxVmZXT3g4Z3pTCm1JYkRrS1dlNHdpWXNkai8wMThjb1FLQmdIUkVyZEc2UFE0azJUVkhHT3c2elhyMEx6a3ZZMWRWY1RZL1lxQWgKRjRSUkgvMW9Uai9pMUJxOG5kNUd5OUNiaWJSWWh5OHVzT3dVWEJqOWF5Y3h1cGs1VmlZTnl4eWczb1NjV1VJUQpQRVhQRkdaUFd4R2NDM3Ivb1ZHZDdHVjBaaWgzS0FuK2ZRR1d3RUZ0VnJWWWRXdHMycFYyMzNVRlFxc0tFWUVDCmtsV1JBb0dCQUt4eHNLWmFOV2kzSHI0b2RlUVZ2Ym43VEVsenZzTzJMZVg5OWd2aEwwRmtSalluU0IvZGtaSTIKblFmb1VxRERIdW9mUXYzQ01zM3QzeFBTOTNJTmlXVUt2TjYzWGxIYUp5R08vUmhDSk40S1FNU3o4MVFMSlBWTwoweFVnaXQxT2doUXpQcXBsY3hZNjk0bEJBVzVUUHZ2Q1BLK3BoMG5IQlBOeFczZlZEaFpyCi0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg==
  kind: Secret
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Secret","metadata":{"annotations":{},"labels":{"app.kubernetes.io/name":"argocd-secret","app.kubernetes.io/part-of":"argocd"},"name":"argocd-secret","namespace":"argocd"},"type":"Opaque"}
    labels:
      app.kubernetes.io/name: argocd-secret
      app.kubernetes.io/part-of: argocd
    name: argocd-secret
    namespace: argocd
  type: Opaque
kind: List
metadata:
