apiVersion: v1
items:
- apiVersion: networking.k8s.io/v1
  kind: Ingress
  metadata:
    annotations:
      argocd.argoproj.io/tracking-id: monitoring-stack:networking.k8s.io/Ingress:monitoring/alertmanager-ingress
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"networking.k8s.io/v1","kind":"Ingress","metadata":{"annotations":{"argocd.argoproj.io/tracking-id":"monitoring-stack:networking.k8s.io/Ingress:monitoring/alertmanager-ingress"},"name":"alertmanager-ingress","namespace":"monitoring"},"spec":{"ingressClassName":"nginx","rules":[{"host":"alertmanager.34.89.208.249.nip.io","http":{"paths":[{"backend":{"service":{"name":"alertmanager","port":{"number":9093}}},"path":"/","pathType":"Prefix"}]}}]}}
    generation: 1
    name: alertmanager-ingress
    namespace: monitoring
  spec:
    ingressClassName: nginx
    rules:
    - host: alertmanager.34.89.208.249.nip.io
      http:
        paths:
        - backend:
            service:
              name: alertmanager
              port:
                number: 9093
          path: /
          pathType: Prefix
    loadBalancer:
      ingress:
      - ip: 10.156.15.202
- apiVersion: networking.k8s.io/v1
  kind: Ingress
  metadata:
    annotations:
      argocd.argoproj.io/tracking-id: monitoring-stack:networking.k8s.io/Ingress:monitoring/grafana-ingress
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"networking.k8s.io/v1","kind":"Ingress","metadata":{"annotations":{"argocd.argoproj.io/tracking-id":"monitoring-stack:networking.k8s.io/Ingress:monitoring/grafana-ingress"},"name":"grafana-ingress","namespace":"monitoring"},"spec":{"ingressClassName":"nginx","rules":[{"host":"grafana.34.89.208.249.nip.io","http":{"paths":[{"backend":{"service":{"name":"grafana","port":{"number":3000}}},"path":"/","pathType":"Prefix"}]}}]}}
    generation: 1
    name: grafana-ingress
    namespace: monitoring
  spec:
    ingressClassName: nginx
    rules:
    - host: grafana.34.89.208.249.nip.io
      http:
        paths:
        - backend:
            service:
              name: grafana
              port:
                number: 3000
          path: /
          pathType: Prefix
    loadBalancer:
      ingress:
      - ip: 10.156.15.202
- apiVersion: networking.k8s.io/v1
  kind: Ingress
  metadata:
    annotations:
      argocd.argoproj.io/tracking-id: monitoring-stack:networking.k8s.io/Ingress:monitoring/prometheus-ingress
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"networking.k8s.io/v1","kind":"Ingress","metadata":{"annotations":{"argocd.argoproj.io/tracking-id":"monitoring-stack:networking.k8s.io/Ingress:monitoring/prometheus-ingress"},"name":"prometheus-ingress","namespace":"monitoring"},"spec":{"ingressClassName":"nginx","rules":[{"host":"prometheus.34.89.208.249.nip.io","http":{"paths":[{"backend":{"service":{"name":"prometheus","port":{"number":9090}}},"path":"/","pathType":"Prefix"}]}}]}}
    generation: 1
    name: prometheus-ingress
    namespace: monitoring
  spec:
    ingressClassName: nginx
    rules:
    - host: prometheus.34.89.208.249.nip.io
      http:
        paths:
        - backend:
            service:
              name: prometheus
              port:
                number: 9090
          path: /
          pathType: Prefix
    loadBalancer:
      ingress:
      - ip: 10.156.15.202
kind: List
metadata:
