apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-custom-app-ingress
  namespace: web-stack
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  ingressClassName: traefik
  rules:
  - host: moja-aplikacia.34.159.144.113.nip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: my-custom-app-svc
            port:
              number: 80
