---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-custom-app-ingress
  namespace: web-stack
  annotations:
spec:
  ingressClassName: nginx
  rules:
  - host: moja-aplikacia.34.89.208.249.nip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: my-custom-app-svc
            port:
              number: 80
