apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - flux-system/gotk-components.yaml
  - flux-system/gotk-sync.yaml
  - lamp-system/app.yaml
  - monitoring/setup.yaml
  - logging/setup.yaml
  - storage/setup.yaml
  - web-stack/setup.yaml
  - my-custom-app/deployment.yaml
  - my-custom-app/ingress.yaml
# Force sync revision Wed Feb 25 10:52:27 UTC 2026
