apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - flux-system
  - logging
  - monitoring
  - lamp-system
  - storage
  - web
  - web-stack
  - my-custom-app
  - vector-config-manual.yaml
