apiVersion: apps/v1
kind: Deployment
metadata:
  name: flux-smoke-test
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flux-smoke-test
  template:
    metadata:
      labels:
        app: flux-smoke-test
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
