apiVersion: v1
items:
- apiVersion: networking.k8s.io/v1
  kind: Ingress
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: '{"apiVersion":"networking.k8s.io/v1","kind":"Ingress","metadata":{"annotations":{"nginx.ingress.kubernetes.io/backend-protocol":"HTTP","nginx.ingress.kubernetes.io/ssl-redirect":"false"},"name":"argocd-final","namespace":"argocd"},"spec":{"ingressClassName":"nginx","rules":[{"host":"argocd.34.89.208.249.nip.io","http":{"paths":[{"backend":{"service":{"name":"argocd-server","port":{"number":80}}},"path":"/","pathType":"Prefix"}]}}]}}

        '
      nginx.ingress.kubernetes.io/backend-protocol: HTTP
      nginx.ingress.kubernetes.io/ssl-redirect: 'false'
    creationTimestamp: '2026-02-26T14:48:18Z'
    generation: 1
    name: argocd-final
    namespace: argocd
    resourceVersion: '191318'
    uid: a13f3cbd-52eb-436a-849a-f679d6318014
  spec:
    ingressClassName: nginx
    rules:
    - host: argocd.34.89.208.249.nip.io
      http:
        paths:
        - backend:
            service:
              name: argocd-server
              port:
                number: 80
          path: /
          pathType: Prefix
  status:
    loadBalancer:
      ingress:
      - ip: 10.156.15.202
kind: List
metadata: {}
